/**
 * ApiAssertions template content
 * Written to: <baseDir>/utils/ApiAssertions.ts
 */

export const API_ASSERTIONS_CONTENT = `/**
 * Typed assertion helpers for API responses
 * Generated by swagger-to-playwright-api-clients
 */

import { expect } from '@playwright/test';
import { logger } from 'swagger-to-playwright-api-clients';

/**
 * Utility class for asserting API response status codes.
 * All status comparisons use numbers — never strings.
 */
export class ApiAssertions {
  /**
   * Assert status equals an exact value
   */
  static expectStatus(actual: number, expected: number): void {
    logger.debug(\`ApiAssertions.expectStatus: actual=\${actual}, expected=\${expected}\`);
    expect(actual, \`Expected status \${expected} but got \${actual}\`).toBe(expected);
  }

  /**
   * Assert status is one of the allowed values
   */
  static expectOneOf(actual: number, allowed: number[]): void {
    logger.debug(\`ApiAssertions.expectOneOf: actual=\${actual}, allowed=[\${allowed.join(', ')}]\`);
    expect(
      allowed.includes(actual),
      \`Expected status to be one of [\${allowed.join(', ')}] but got \${actual}\`,
    ).toBe(true);
  }

  /**
   * Assert status is a 2xx success code
   */
  static expectSuccess(status: number): void {
    logger.debug(\`ApiAssertions.expectSuccess: status=\${status}\`);
    expect(
      status >= 200 && status < 300,
      \`Expected 2xx success but got \${status}\`,
    ).toBe(true);
  }

  /**
   * Assert status is a 4xx client error
   */
  static expectClientError(status: number): void {
    logger.debug(\`ApiAssertions.expectClientError: status=\${status}\`);
    expect(
      status >= 400 && status < 500,
      \`Expected 4xx client error but got \${status}\`,
    ).toBe(true);
  }

  /**
   * Assert status is NOT a 5xx server error
   */
  static expectNoServerError(status: number): void {
    logger.debug(\`ApiAssertions.expectNoServerError: status=\${status}\`);
    expect(
      status < 500,
      \`Expected no server error but got \${status}\`,
    ).toBe(true);
  }

  /**
   * Check if status is a 2xx success (non-asserting boolean helper)
   */
  static isSuccess(status: number): boolean {
    logger.debug(\`ApiAssertions.isSuccess: status=\${status} -> \${status >= 200 && status < 300}\`);
    return status >= 200 && status < 300;
  }

  /**
   * Check if status is a 4xx client error (non-asserting boolean helper)
   */
  static isClientError(status: number): boolean {
    logger.debug(\`ApiAssertions.isClientError: status=\${status} -> \${status >= 400 && status < 500}\`);
    return status >= 400 && status < 500;
  }

  /**
   * Assert status is a 5xx server error
   */
  static expectServerError(status: number): void {
    logger.debug(\`ApiAssertions.expectServerError: status=\${status}\`);
    expect(
      status >= 500,
      \`Expected 5xx server error but got \${status}\`,
    ).toBe(true);
  }

  /**
   * Assert response has a specific header key
   */
  static expectHeader(headers: Record<string, string>, key: string): void {
    const lowerKey = key.toLowerCase();
    logger.debug(\`ApiAssertions.expectHeader: checking for '\${lowerKey}'\`);
    expect(lowerKey in headers, \`Expected header '\${lowerKey}' to be present\`).toBe(true);
  }

  /**
   * Assert response header equals a specific value
   */
  static expectHeaderValue(headers: Record<string, string>, key: string, expected: string): void {
    const lowerKey = key.toLowerCase();
    logger.debug(\`ApiAssertions.expectHeaderValue: '\${lowerKey}' expected='\${expected}'\`);
    expect(headers[lowerKey], \`Expected header '\${lowerKey}' to be '\${expected}'\`).toBe(expected);
  }

  /**
   * Assert body is not empty (not null, not undefined, not empty object/array)
   */
  static expectNonEmptyBody(body: unknown): void {
    logger.debug('ApiAssertions.expectNonEmptyBody');
    expect(body, 'Expected body to be defined').toBeDefined();
    expect(body, 'Expected body to not be null').not.toBeNull();
  }
}
`;
