/**
 * SecurityPayloads template content
 * Written to: <baseDir>/utils/SecurityPayloads.ts
 */

export const SECURITY_PAYLOADS_CONTENT = `/**
 * Security test payloads for injection and abuse testing
 * Generated by swagger-to-playwright-api-clients
 */

import { logger } from 'swagger-to-playwright-api-clients';

/**
 * Pre-built attack payloads for security test generation.
 * Use with security test skill: \`#generate-security-tests\`
 */
export class SecurityPayloads {
  // ── SQL Injection ────────────────────────────────────────────────────

  static readonly SQL_INJECTION: string[] = [
    "' OR '1'='1",
    "' OR '1'='1' --",
    "'; DROP TABLE users; --",
    "' UNION SELECT NULL, NULL, NULL --",
    "1; WAITFOR DELAY '0:0:5' --",
    "' AND 1=CONVERT(int, (SELECT TOP 1 table_name FROM information_schema.tables)) --",
    "admin'--",
    "1' ORDER BY 1 --",
  ];

  // ── XSS (Cross-Site Scripting) ───────────────────────────────────────

  static readonly XSS: string[] = [
    '<script>alert("XSS")</script>',
    '<img src=x onerror=alert(1)>',
    '"><script>alert(document.cookie)</script>',
    "javascript:alert('XSS')",
    '<svg onload=alert(1)>',
    '<body onload=alert(1)>',
    '<iframe src="javascript:alert(1)">',
    '{{constructor.constructor("return this")().alert(1)}}',
  ];

  // ── SSTI (Server-Side Template Injection) ────────────────────────────

  static readonly SSTI: string[] = [
    '{{7*7}}',
    '\${7*7}',
    '<%= 7*7 %>',
    '#{7*7}',
    '*{7*7}',
    '{{config}}',
    '{{self.__class__.__mro__[1].__subclasses__()}}',
  ];

  // ── Path Traversal ───────────────────────────────────────────────────

  static readonly PATH_TRAVERSAL: string[] = [
    '../../../etc/passwd',
    '..\\\\\\\\..\\\\\\\\..\\\\\\\\windows\\\\\\\\system32\\\\\\\\config\\\\\\\\sam',
    '....//....//....//etc/passwd',
    '%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd',
    '/etc/passwd%00.jpg',
    '..%252f..%252f..%252fetc/passwd',
  ];

  // ── Command Injection ────────────────────────────────────────────────

  static readonly COMMAND_INJECTION: string[] = [
    '; ls -la',
    '| cat /etc/passwd',
    '\`whoami\`',
    '$(whoami)',
    '&& echo vulnerable',
    '|| echo vulnerable',
  ];

  // ── NoSQL Injection ──────────────────────────────────────────────────

  static readonly NOSQL_INJECTION: (string | Record<string, unknown>)[] = [
    '{"\\$gt": ""}',
    '{"\\$ne": null}',
    '{"\\$regex": ".*"}',
    { '\\$gt': '' },
    { '\\$ne': null },
    { '\\$regex': '.*' },
  ];

  // ── JWT Attack Tokens ────────────────────────────────────────────────

  static readonly JWT_ATTACKS: string[] = [
    // alg: none
    'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiIxMjM0NTY3ODkwIn0.',
    // Empty signature
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.',
    // Expired token
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxfQ.invalid',
  ];

  // ── Header Injection ─────────────────────────────────────────────────

  static readonly HEADER_INJECTION: Record<string, string>[] = [
    { 'x-forwarded-for': '127.0.0.1' },
    { 'x-original-url': '/admin' },
    { 'x-rewrite-url': '/admin' },
    { host: 'evil.com' },
    { 'content-type': 'application/xml' },
  ];

  // ── Oversized Payloads ───────────────────────────────────────────────

  static oversizedString(sizeKB: number = 100): string {
    logger.debug(\`SecurityPayloads.oversizedString: generating \${sizeKB}KB payload\`);
    return 'A'.repeat(sizeKB * 1024);
  }

  static oversizedArray(length: number = 10000): unknown[] {
    logger.debug(\`SecurityPayloads.oversizedArray: generating array of \${length} items\`);
    return Array.from({ length }, (_, i) => ({ id: i, value: 'x'.repeat(100) }));
  }

  // ── Auth payloads ────────────────────────────────────────────────────

  static readonly MALFORMED_BEARER: string[] = [
    'Bearer ',
    'Bearer invalid-token',
    'Bearer null',
    'Bearer undefined',
    'Basic dXNlcjpwYXNz',     // wrong scheme
    'bearer valid-looking-token', // lowercase scheme
    '',
  ];

  /**
   * Get all payloads for a given category
   */
  static getPayloads(category: 'sql' | 'xss' | 'ssti' | 'path' | 'command' | 'nosql' | 'jwt' | 'header' | 'bearer'): unknown[] {
    logger.debug(\`SecurityPayloads.getPayloads: category=\${category}\`);
    const map: Record<string, unknown[]> = {
      sql: SecurityPayloads.SQL_INJECTION,
      xss: SecurityPayloads.XSS,
      ssti: SecurityPayloads.SSTI,
      path: SecurityPayloads.PATH_TRAVERSAL,
      command: SecurityPayloads.COMMAND_INJECTION,
      nosql: SecurityPayloads.NOSQL_INJECTION,
      jwt: SecurityPayloads.JWT_ATTACKS,
      header: SecurityPayloads.HEADER_INJECTION,
      bearer: SecurityPayloads.MALFORMED_BEARER,
    };
    return map[category] || [];
  }
}
`;
