/**
 * SetupHelpers template content
 * Written to: <baseDir>/helpers/SetupHelpers.ts
 */

export const SETUP_HELPERS_CONTENT = `/**
 * Precondition helpers for test setup and teardown
 * Generated by swagger-to-playwright-api-clients
 *
 * Two example helpers are provided as a pattern. Add your own
 * domain-specific helpers following the same conventions:
 *   - Setup methods throw on failure (so the test doesn't run with bad data)
 *   - Teardown methods swallow errors (so cleanup doesn't mask test failures)
 *   - All methods log via logger
 */

import { logger } from 'swagger-to-playwright-api-clients';
import type { BaseAPIClient, APIResponseResult } from '../clients/BaseAPIClient';

export class SetupHelpers {

  /**
   * Create a resource via POST. Throws on non-2xx.
   *
   * Example:
   *   const { body } = await SetupHelpers.createResource(client, '/users', { name: 'Test' }, 'user');
   */
  static async createResource<T = unknown>(
    client: BaseAPIClient,
    endpoint: string,
    payload: unknown,
    label: string = 'resource',
  ): Promise<APIResponseResult<T>> {
    logger.info('SetupHelpers.createResource: creating ' + label + ' at ' + endpoint);
    const result = await client.post<T>(endpoint, payload);
    if (result.status < 200 || result.status >= 300) {
      throw new Error(
        'Setup failed: could not create ' + label + ' (status ' + result.status + ')'
      );
    }
    logger.info('SetupHelpers.createResource: ' + label + ' created (status ' + result.status + ')');
    return result;
  }

  /**
   * Delete a resource via DELETE. Swallows errors so cleanup never masks test failures.
   *
   * Example:
   *   await SetupHelpers.deleteResource(client, '/users/' + userId, 'user');
   */
  static async deleteResource(
    client: BaseAPIClient,
    endpoint: string,
    label: string = 'resource',
  ): Promise<void> {
    try {
      logger.info('SetupHelpers.deleteResource: deleting ' + label + ' at ' + endpoint);
      const result = await client.delete(endpoint);
      logger.info('SetupHelpers.deleteResource: ' + label + ' deleted (status ' + result.status + ')');
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      logger.warn('SetupHelpers.deleteResource: failed to delete ' + label + ' — ' + msg);
    }
  }
}
`;
