/**
 * TestDataGenerator template content
 * Written to: <baseDir>/utils/TestDataGenerator.ts
 */

export const TEST_DATA_GENERATOR_CONTENT = `/**
 * Test data builder utilities for API payloads
 * Generated by swagger-to-playwright-api-clients
 *
 * Provides random data generators, boundary values, date helpers,
 * and a generic builder utility. Extend with domain-specific builders
 * that match your generated Request interfaces.
 */

import { logger } from 'swagger-to-playwright-api-clients';

// ── Character sets ───────────────────────────────────────────────────────

const CHARS_LOWER = 'abcdefghijklmnopqrstuvwxyz';
const CHARS_UPPER = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const DIGITS = '0123456789';
const ALPHANUMERIC = CHARS_LOWER + CHARS_UPPER + DIGITS;
const HEX_CHARS = '0123456789abcdef';
const SPECIAL = '!@#$%^&*()-_=+[]{}|;:,.<>?';

function randomChars(charset: string, length: number): string {
  let result = '';
  for (let i = 0; i < length; i++) {
    result += charset[Math.floor(Math.random() * charset.length)];
  }
  return result;
}

// ── First / Last name pools ──────────────────────────────────────────────

const FIRST_NAMES = [
  'James', 'Mary', 'Robert', 'Patricia', 'John', 'Jennifer', 'Michael',
  'Linda', 'David', 'Elizabeth', 'William', 'Barbara', 'Richard', 'Susan',
  'Joseph', 'Jessica', 'Thomas', 'Sarah', 'Christopher', 'Karen',
  'Amit', 'Priya', 'Chen', 'Yuki', 'Ahmed', 'Fatima', 'Carlos', 'Sofia',
];

const LAST_NAMES = [
  'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller',
  'Davis', 'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Gonzalez',
  'Wilson', 'Anderson', 'Thomas', 'Taylor', 'Moore', 'Jackson', 'Martin',
  'Patel', 'Kim', 'Nakamura', 'Ali', 'Silva', 'Mueller', 'Johansson',
];

const DOMAINS = [
  'test.example.com', 'qa.example.com', 'staging.example.com',
  'demo.test.io', 'autotest.dev',
];

const COUNTRY_CODES = [
  '+1', '+44', '+91', '+49', '+33', '+81', '+86', '+55', '+61', '+7',
];

// ── Random generators ────────────────────────────────────────────────────

export const random = {
  /**
   * Random string of lowercase letters
   */
  string(length: number = 10): string {
    const result = randomChars(CHARS_LOWER, length);
    logger.debug(\`random.string(\${length}) -> "\${result}"\`);
    return result;
  },

  /**
   * Random alphanumeric string (a-z, A-Z, 0-9)
   */
  alphanumeric(length: number = 10): string {
    const result = randomChars(ALPHANUMERIC, length);
    logger.debug(\`random.alphanumeric(\${length}) -> "\${result}"\`);
    return result;
  },

  /**
   * Random hex string
   */
  hex(length: number = 16): string {
    const result = randomChars(HEX_CHARS, length);
    logger.debug(\`random.hex(\${length}) -> "\${result}"\`);
    return result;
  },

  /**
   * Random email address (unique per call)
   */
  email(domain?: string): string {
    const d = domain || DOMAINS[Math.floor(Math.random() * DOMAINS.length)];
    const local = 'test+' + Date.now().toString(36) + randomChars(CHARS_LOWER, 4);
    const result = local + '@' + d;
    logger.debug(\`random.email() -> "\${result}"\`);
    return result;
  },

  /**
   * Random mobile/phone number with country code
   */
  mobile(countryCode?: string): string {
    const cc = countryCode || COUNTRY_CODES[Math.floor(Math.random() * COUNTRY_CODES.length)];
    const number = randomChars(DIGITS, 10);
    const result = cc + number;
    logger.debug(\`random.mobile() -> "\${result}"\`);
    return result;
  },

  /**
   * Random UUID v4
   */
  uuid(): string {
    const hex = randomChars(HEX_CHARS, 32);
    const result = [
      hex.slice(0, 8), hex.slice(8, 12),
      '4' + hex.slice(13, 16),
      ((parseInt(hex[16], 16) & 0x3) | 0x8).toString(16) + hex.slice(17, 20),
      hex.slice(20, 32),
    ].join('-');
    logger.debug(\`random.uuid() -> "\${result}"\`);
    return result;
  },

  /**
   * Random integer between min (inclusive) and max (inclusive)
   */
  integer(min: number = 0, max: number = 1000): number {
    const result = Math.floor(Math.random() * (max - min + 1)) + min;
    logger.debug(\`random.integer(\${min}, \${max}) -> \${result}\`);
    return result;
  },

  /**
   * Random float between min (inclusive) and max (exclusive)
   */
  float(min: number = 0, max: number = 1000, decimals: number = 2): number {
    const raw = Math.random() * (max - min) + min;
    const result = parseFloat(raw.toFixed(decimals));
    logger.debug(\`random.float(\${min}, \${max}) -> \${result}\`);
    return result;
  },

  /**
   * Random boolean
   */
  boolean(): boolean {
    const result = Math.random() < 0.5;
    logger.debug(\`random.boolean() -> \${result}\`);
    return result;
  },

  /**
   * Random first name
   */
  firstName(): string {
    const result = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
    logger.debug(\`random.firstName() -> "\${result}"\`);
    return result;
  },

  /**
   * Random last name
   */
  lastName(): string {
    const result = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
    logger.debug(\`random.lastName() -> "\${result}"\`);
    return result;
  },

  /**
   * Random full name
   */
  fullName(): string {
    const result = random.firstName() + ' ' + random.lastName();
    logger.debug(\`random.fullName() -> "\${result}"\`);
    return result;
  },

  /**
   * Random strong password (12+ chars, mixed case, digits, special)
   */
  password(length: number = 16): string {
    // Guarantee at least one of each category
    const upper = randomChars(CHARS_UPPER, 1);
    const lower = randomChars(CHARS_LOWER, 1);
    const digit = randomChars(DIGITS, 1);
    const special = randomChars(SPECIAL, 1);
    const rest = randomChars(ALPHANUMERIC + SPECIAL, Math.max(0, length - 4));
    // Shuffle
    const chars = (upper + lower + digit + special + rest).split('');
    for (let i = chars.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [chars[i], chars[j]] = [chars[j], chars[i]];
    }
    const result = chars.join('');
    logger.debug(\`random.password(\${length}) -> [REDACTED]\`);
    return result;
  },

  /**
   * Random URL
   */
  url(protocol: string = 'https'): string {
    const domain = randomChars(CHARS_LOWER, 8) + '.example.com';
    const pathSegment = '/' + randomChars(CHARS_LOWER, 6);
    const result = protocol + '://' + domain + pathSegment;
    logger.debug(\`random.url() -> "\${result}"\`);
    return result;
  },

  /**
   * Random IPv4 address
   */
  ipv4(): string {
    const octets = Array.from({ length: 4 }, () => Math.floor(Math.random() * 256));
    const result = octets.join('.');
    logger.debug(\`random.ipv4() -> "\${result}"\`);
    return result;
  },

  /**
   * Random hex color code
   */
  hexColor(): string {
    const result = '#' + randomChars(HEX_CHARS, 6);
    logger.debug(\`random.hexColor() -> "\${result}"\`);
    return result;
  },

  /**
   * Pick a random element from an array
   */
  fromArray<T>(arr: T[]): T {
    const index = Math.floor(Math.random() * arr.length);
    const result = arr[index];
    logger.debug(\`random.fromArray() -> index \${index}\`);
    return result;
  },

  /**
   * Pick N unique random elements from an array
   */
  sampleArray<T>(arr: T[], count: number): T[] {
    const shuffled = [...arr].sort(() => Math.random() - 0.5);
    const result = shuffled.slice(0, Math.min(count, arr.length));
    logger.debug(\`random.sampleArray() -> \${result.length} items\`);
    return result;
  },

  /**
   * Random ISO date string (YYYY-MM-DD) within a range
   */
  dateString(start?: Date, end?: Date): string {
    const s = start || new Date(2020, 0, 1);
    const e = end || new Date();
    const timestamp = s.getTime() + Math.random() * (e.getTime() - s.getTime());
    const result = new Date(timestamp).toISOString().split('T')[0];
    logger.debug(\`random.dateString() -> "\${result}"\`);
    return result;
  },

  /**
   * Random ISO datetime string
   */
  isoDateTime(start?: Date, end?: Date): string {
    const s = start || new Date(2020, 0, 1);
    const e = end || new Date();
    const timestamp = s.getTime() + Math.random() * (e.getTime() - s.getTime());
    const result = new Date(timestamp).toISOString();
    logger.debug(\`random.isoDateTime() -> "\${result}"\`);
    return result;
  },

  /**
   * Random country code (e.g. '+1', '+44')
   */
  countryCode(): string {
    return random.fromArray(COUNTRY_CODES);
  },

  /**
   * Random paragraph of lorem-ish text
   */
  paragraph(sentences: number = 3): string {
    const words = [
      'lorem', 'ipsum', 'dolor', 'sit', 'amet', 'consectetur', 'adipiscing',
      'elit', 'sed', 'do', 'eiusmod', 'tempor', 'incididunt', 'ut', 'labore',
      'et', 'dolore', 'magna', 'aliqua', 'enim', 'ad', 'minim', 'veniam',
    ];
    const result = Array.from({ length: sentences }, () => {
      const len = random.integer(5, 12);
      const s = Array.from({ length: len }, () => random.fromArray(words)).join(' ');
      return s.charAt(0).toUpperCase() + s.slice(1) + '.';
    }).join(' ');
    logger.debug(\`random.paragraph(\${sentences}) -> "\${result.slice(0, 50)}..."\`);
    return result;
  },
};

// ── Boundary / edge-case values ──────────────────────────────────────────

export const boundary = {
  emptyString: '',
  unicodeString: '\\\\u4f60\\\\u597d\\\\u4e16\\\\u754c \\\\ud83d\\\\ude80 \\\\u00e9\\\\u00e0\\\\u00fc\\\\u00df',
  longString: 'a'.repeat(10_000),
  negativeNumber: -1,
  zero: 0,
  maxSafeInteger: Number.MAX_SAFE_INTEGER,
  specialChars: '<script>alert(1)</script>',
  sqlInjection: "' OR 1=1 --",
  emptyArray: [] as unknown[],
  nullValue: null,
  whitespaceOnly: '   \\\\t\\\\n  ',
  singleChar: 'x',
  maxLengthEmail: 'a'.repeat(64) + '@' + 'b'.repeat(63) + '.com',
  negativeFloat: -0.001,
  largeNumber: 999_999_999_999,
};

// ── Date helpers ─────────────────────────────────────────────────────────

export const dates = {
  today: (): string => new Date().toISOString().split('T')[0],
  yesterday: (): string => {
    const d = new Date();
    d.setDate(d.getDate() - 1);
    return d.toISOString().split('T')[0];
  },
  tomorrow: (): string => {
    const d = new Date();
    d.setDate(d.getDate() + 1);
    return d.toISOString().split('T')[0];
  },
  thisMonthStart: (): string => {
    const d = new Date();
    return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().split('T')[0];
  },
  thisMonthEnd: (): string => {
    const d = new Date();
    return new Date(d.getFullYear(), d.getMonth() + 1, 0).toISOString().split('T')[0];
  },
  daysFromNow: (n: number): string => {
    const d = new Date();
    d.setDate(d.getDate() + n);
    return d.toISOString().split('T')[0];
  },
  daysAgo: (n: number): string => {
    const d = new Date();
    d.setDate(d.getDate() - n);
    return d.toISOString().split('T')[0];
  },
  nowISO: (): string => new Date().toISOString(),
  startOfYear: (): string => {
    const d = new Date();
    return new Date(d.getFullYear(), 0, 1).toISOString().split('T')[0];
  },
  endOfYear: (): string => {
    const d = new Date();
    return new Date(d.getFullYear(), 11, 31).toISOString().split('T')[0];
  },
};

// ── Generic builder ──────────────────────────────────────────────────────

/**
 * Create a base object and allow partial overrides.
 * Use this to build domain-specific payload factories.
 */
export function buildWith<T extends Record<string, unknown>>(
  defaults: T,
  overrides?: Partial<T>,
): T {
  logger.debug('buildWith: merging defaults with overrides');
  return { ...defaults, ...overrides };
}

// ── Public API ───────────────────────────────────────────────────────────

/**
 * TestDataGenerator — single import for all test data utilities.
 *
 * Extend with domain-specific builders, e.g.:
 *
 *   // In your project, add to this object or create a separate file:
 *   export const signup = {
 *     build: (overrides?: Partial<PostSignupPatientRequest>) =>
 *       buildWith<PostSignupPatientRequest>({
 *         email: random.email(),
 *         password: random.password(),
 *         firstName: random.firstName(),
 *       }, overrides),
 *   };
 */
export const TestDataGenerator = {
  random,
  boundary,
  dates,
  buildWith,
};

export default TestDataGenerator;
`;
