/**
 * TypeValidator template content
 * Written to: <baseDir>/utils/TypeValidator.ts
 */

export const TYPE_VALIDATOR_CONTENT = `/**
 * Runtime structural type checks on response body fields
 * Generated by swagger-to-playwright-api-clients
 */

import { expect } from '@playwright/test';
import { logger } from 'swagger-to-playwright-api-clients';

/**
 * Utility class for validating the runtime types of optional/nullable fields
 * returned in API response bodies.
 */
export class TypeValidator {
  /**
   * Expect field to be string | undefined
   */
  static expectOptionalString(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalString: '\${field}' = \${typeof obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be string | undefined\`).toBe('string');
    }
  }

  /**
   * Expect field to be number | undefined
   */
  static expectOptionalNumber(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalNumber: '\${field}' = \${typeof obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be number | undefined\`).toBe('number');
    }
  }

  /**
   * Expect field to be boolean | undefined
   */
  static expectOptionalBoolean(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalBoolean: '\${field}' = \${typeof obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be boolean | undefined\`).toBe('boolean');
    }
  }

  /**
   * Expect field to be array | undefined
   */
  static expectOptionalArray(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalArray: '\${field}' isArray=\${Array.isArray(obj[field])}\`);
    if (obj[field] !== undefined) {
      expect(Array.isArray(obj[field]), \`Expected '\${field}' to be array | undefined\`).toBe(true);
    }
  }

  /**
   * Expect field to be array | null | undefined
   */
  static expectNullableArray(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectNullableArray: '\${field}' value=\${obj[field]}\`);
    if (obj[field] !== undefined && obj[field] !== null) {
      expect(Array.isArray(obj[field]), \`Expected '\${field}' to be array | null | undefined\`).toBe(true);
    }
  }

  /**
   * Expect field to be number[] | undefined
   */
  static expectOptionalNumberArray(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalNumberArray: '\${field}'\`);
    if (obj[field] !== undefined) {
      expect(Array.isArray(obj[field]), \`Expected '\${field}' to be number[] | undefined\`).toBe(true);
      for (const item of obj[field] as unknown[]) {
        expect(typeof item, \`Expected items in '\${field}' to be numbers\`).toBe('number');
      }
    }
  }

  /**
   * Expect field to be string[] | undefined
   */
  static expectOptionalStringArray(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalStringArray: '\${field}'\`);
    if (obj[field] !== undefined) {
      expect(Array.isArray(obj[field]), \`Expected '\${field}' to be string[] | undefined\`).toBe(true);
      for (const item of obj[field] as unknown[]) {
        expect(typeof item, \`Expected items in '\${field}' to be strings\`).toBe('string');
      }
    }
  }

  /**
   * Expect field to be a valid ISO 8601 date string | undefined
   */
  static expectOptionalISODate(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalISODate: '\${field}' = \${obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be string | undefined\`).toBe('string');
      const date = new Date(obj[field] as string);
      expect(isNaN(date.getTime()), \`Expected '\${field}' to be a valid ISO date\`).toBe(false);
    }
  }

  /**
   * Expect field to be a valid email string | undefined
   */
  static expectOptionalEmail(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalEmail: '\${field}' = \${obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be string\`).toBe('string');
      const emailRegex = /^[^\\\\s@]+@[^\\\\s@]+\\\\.[^\\\\s@]+$/;
      expect(
        emailRegex.test(obj[field] as string),
        \`Expected '\${field}' to be a valid email\`,
      ).toBe(true);
    }
  }

  /**
   * Expect field to be a valid URL string | undefined
   */
  static expectOptionalUrl(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalUrl: '\${field}' = \${obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be string\`).toBe('string');
      expect(() => new URL(obj[field] as string), \`Expected '\${field}' to be a valid URL\`).not.toThrow();
    }
  }

  /**
   * Expect field to be an object | undefined
   */
  static expectOptionalObject(obj: Record<string, unknown>, field: string): void {
    logger.debug(\`TypeValidator.expectOptionalObject: '\${field}' = \${typeof obj[field]}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be object | undefined\`).toBe('object');
      expect(obj[field], \`Expected '\${field}' to not be null\`).not.toBeNull();
      expect(Array.isArray(obj[field]), \`Expected '\${field}' to not be an array\`).toBe(false);
    }
  }

  /**
   * Expect field to be an enum value from a given set | undefined
   */
  static expectOptionalEnum(obj: Record<string, unknown>, field: string, allowed: unknown[]): void {
    logger.debug(\`TypeValidator.expectOptionalEnum: '\${field}' = \${obj[field]}, allowed=[\${allowed.join(', ')}]\`);
    if (obj[field] !== undefined) {
      expect(
        allowed.includes(obj[field]),
        \`Expected '\${field}' to be one of [\${allowed.join(', ')}] but got '\${obj[field]}'\`,
      ).toBe(true);
    }
  }

  /**
   * Expect field to be an array of objects, each containing the specified keys
   */
  static expectArrayOfObjects(
    obj: Record<string, unknown>,
    field: string,
    expectedKeys: string[],
  ): void {
    logger.debug(\`TypeValidator.expectArrayOfObjects: '\${field}' keys=[\${expectedKeys.join(', ')}]\`);
    if (obj[field] !== undefined) {
      expect(Array.isArray(obj[field]), \`Expected '\${field}' to be an array\`).toBe(true);
      for (const item of obj[field] as Record<string, unknown>[]) {
        for (const key of expectedKeys) {
          expect(key in item, \`Expected object in '\${field}' to have key '\${key}'\`).toBe(true);
        }
      }
    }
  }

  /**
   * Expect field to match a regex pattern | undefined
   */
  static expectOptionalPattern(obj: Record<string, unknown>, field: string, pattern: RegExp): void {
    logger.debug(\`TypeValidator.expectOptionalPattern: '\${field}' pattern=\${pattern}\`);
    if (obj[field] !== undefined) {
      expect(typeof obj[field], \`Expected '\${field}' to be string\`).toBe('string');
      expect(
        pattern.test(obj[field] as string),
        \`Expected '\${field}' to match pattern \${pattern}\`,
      ).toBe(true);
    }
  }
}
`;
